[build]
command = "pnpm build || ( npm install pnpm && pnpm build )"
publish = "build/"
[build.environment] 
  NODE_VERSION = "16.15.1"
  NPM_FLAGS = "--version"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

