[build]
environment = { NODE_ENV = "production", NODE_VERSION = "16.1.0" }
command = "npm install && npm run build:css && npm run build:prod"
publish = "build/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/categories/personal-development"
  to = "/categories/life/"

