[build]
command = "corepack enable && pnpm i --store=node_modules/.pnpm-store && pnpm run build"
publish = "build/"
[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "child-src 'self'; default-src 'self'; style-src 'self' 'unsafe-inline' https://cdn.iubenda.com https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; form-action 'self' https://taocode.us6.list-manage.com; script-src 'self' 'unsafe-inline' https://cdn.iubenda.com https://utteranc.es; connect-src 'self' https://api.github.com; img-src 'self' data: https://cdn.iubenda.com https://avatars.githubusercontent.com; base-uri 'self'; frame-src 'self' https://www.iubenda.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), document-domain=(), encrypted-media=(), gyroscope=(), interest-cohort=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), sync-xhr=(), usb=(), xr-spatial-tracking=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
